name: build-and-publish

on: [pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - uses: actions/checkout@v2
      - run: sudo mkdir -p /artifacts/

      - name: Build
        run: sudo go build -o /artifacts/echolife-exporter

      - uses: actions/upload-artifact@v2.2.3
        with:
          name: echolife-exporter
          path: /artifacts/

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@master

      - uses: actions/download-artifact@v2.0.9
        with:
          name: echolife-exporter
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./ 
          file: ./Dockerfile
          push: true
          tags: virtualthoughts/echolife-exporter:latest,virtualthoughts/echolife-exporter:0.${{ github.run_number }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
